### ISSUE TITLE
Mixed Text Option

### ISSUE THREAD

**Issue by gasyoun** [sanskrit/detect.py#2]
R   वाग्
R   वाङ्
R   वाचं
R   वाचालवति
R   वाडेयीपुत्र

"Detected as devanagari" is perfectly fine. But there might be texts with mixed input separated like this dictionary list with non-devanagari letters. Should we count? Maybe, I do not know.

**Comment by akprasad** [comment]
Closing since I don't have the time to make this change (though I'm open to any PRs). I think the code is fast enough to enable something like:

```
tokens = text.split()
encodings = [detect(t) for t in tokens]
```

Which should cover most of the same use cases.
