### ISSUE TITLE
Add Encoding Schemes

### ISSUE THREAD

**Issue by gasyoun** [sanskrit/detect.py#5]
Add Encodings, not only transliteration schemes, please. Otherwise a task like https://groups.google.com/forum/#!topic/sanskrit-programmers/5uXgIWv6KHY never gets solved. I'm converting non-unicode devanagari file to unicode, but India is rich in encodings and I would not want to mess things.
https://sites.google.com/site/technicalhindi/home/converters would be the list that has them all. But you need to know what is before you. In my case - no idea, font names obscure.

**Comment by akprasad** [comment]
Closing due to lack of time (though I'm open to PRs). If this is still an issue, I think it's better solved with search and replace.
